google_auth_security_login:
    path: /auth/login
    defaults: { _controller: 'google_auth.controller.google::login' }

google_auth_security_register:
    path: /auth/register
    defaults: { _controller: 'google_auth.controller.google::register' }

google_auth_connect_google_check:
    path: /auth/check
    defaults: { _controller: 'google_auth.controller.google::check' }

google_auth_security_logout:
    path: /auth/logout
    defaults: { _controller: 'google_auth.controller.google::logout' }

google_auth_security_logout_force:
    path: /auth/logout/force
    defaults: { _controller: 'google_auth.controller.google::forceLogout' }


admin_user_index:
    path: /admin/users
    defaults: { _controller: 'google_auth.controller.user::index' }

admin_user_edit:
    path: /admin/users/{username}
    defaults: { _controller: 'google_auth.controller.user::edit' }

admin_user_enable_disable:
    path: /admin/users/{id}/enableDisable
    defaults: { _controller: 'google_auth.controller.user::enableDisable' }
